//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperMarket.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class supermarket_dbEntities1 : DbContext
    {
        public supermarket_dbEntities1()
            : base("name=supermarket_dbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_cliente> tb_cliente { get; set; }
        public virtual DbSet<tb_compra> tb_compra { get; set; }
        public virtual DbSet<tb_compra_has_tb_produto> tb_compra_has_tb_produto { get; set; }
        public virtual DbSet<tb_enderecocliente> tb_enderecocliente { get; set; }
        public virtual DbSet<tb_produto> tb_produto { get; set; }
    }
}
