//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_compra_has_tb_produto
    {
        public int tb_compra_idtb_compra { get; set; }
        public int tb_produto_idtb_produto { get; set; }
        public int ds_quantidade { get; set; }
    
        public virtual tb_compra tb_compra { get; set; }
        public virtual tb_produto tb_produto { get; set; }
    }
}
