//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_cliente()
        {
            this.tb_compra = new HashSet<tb_compra>();
            this.tb_enederecocliente = new HashSet<tb_enederecocliente>();
        }
    
        public int idtb_cliente { get; set; }
        public string nm_cliente { get; set; }
        public string ds_cpf_cnpj { get; set; }
        public int ds_idade { get; set; }
        public string ds_sexo { get; set; }
        public string ds_tipo_pessoa { get; set; }
        public System.DateTime dt_cadastro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_compra> tb_compra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_enederecocliente> tb_enederecocliente { get; set; }
    }
}
