//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_enderecocliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_enderecocliente()
        {
            this.tb_cliente = new HashSet<tb_cliente>();
        }
    
        public int idtb_enderecocliente { get; set; }
        public string nm_endereco { get; set; }
        public string nm_cidade { get; set; }
        public string nm_estado { get; set; }
        public string ds_cep { get; set; }
        public int ds_numero { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_cliente> tb_cliente { get; set; }
    }
}
