//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_enederecocliente
    {
        public int idtb_enderecocliente { get; set; }
        public string nm_endereco { get; set; }
        public string ds_cep { get; set; }
        public string nm_cidade { get; set; }
        public string nm_estado { get; set; }
        public int ds_numero { get; set; }
        public string nm_bairro { get; set; }
        public int tb_cliente_idtb_cliente { get; set; }
    
        public virtual tb_cliente tb_cliente { get; set; }
    }
}
